apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prestos.prestocontroller.prestosql.io
spec:
  group: prestocontroller.prestosql.io
  version: v1alpha1
  names:
    kind: Presto
    singular: presto
    plural: prestos
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            workers:
              type: integer
              minimum: 1
              maximum: 10