apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: presto-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: presto-coordinator
  template:
    metadata:
      labels:
        name: presto-coordinator
    spec:
      containers:
        - name: presto-coordinator
          image: gcr.io/learn-227713/presto:latest
          imagePullPolicy: Always
#          command: [ "/bin/bash", "-c", "--" ]
#          args: [ "while true; do sleep 30; done;" ]
          ports:
            - containerPort: 8080
          env:
              - name: DISCOVERY_URL
                value: http://debug:8080
          volumeMounts:
            - name: config
              mountPath: /init/config
            - name: catalog
              mountPath: /init/config/catalog
      volumes:
        - name: config
          configMap:
            name: coordinator-config
        - name: catalog
          configMap:
            name: catalog

---

apiVersion: v1
kind: Service
metadata:
  name: debug
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: presto-coordinator

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: presto-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      name: presto-worker
  template:
    metadata:
      labels:
        name: presto-worker
    spec:
      containers:
        - name: presto-worker
          image: gcr.io/learn-227713/presto:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DISCOVERY_URL
              value: http://debug:8080
          volumeMounts:
            - name: config
              mountPath: /init/config
            - name: catalog
              mountPath: /init/config/catalog
      volumes:
        - name: config
          configMap:
            name: worker-config
        - name: catalog
          configMap:
            name: catalog