apiVersion: prestocontroller.prestosql.io/v1alpha1
kind: Presto
metadata:
  name: presto-cluster
spec:
  clusterName: star-presto
  replicas: 2
  coordinatorConfig: coordinator-config
  workerConfig: worker-config
  catalogConfig: catalog
